In [4]:
# https://qiita.com/jyori112/items/a15658d1dd17c421e1e2

import numpy as np
import datetime

#　一次元配列
arr = np.asarray([1,2,3])
arr



array([1, 2, 3])

In [3]:
# タイプ指定
arr = np.asarray([1,2,3], dtype=np.float32)
arr


array([ 1.,  2.,  3.], dtype=float32)

In [6]:
# 型変更
i_arr = np.asarray([1,2,3], dtype=np.int32)
f_arr = i_arr.astype(np.float32)
f_arr,i_arr


(array([ 1.,  2.,  3.], dtype=float32), array([1, 2, 3], dtype=int32))

In [7]:

# 多次元配列
arr = np.asarray([ [1,2,3], [4,5,6] ])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# python
[1,2,3]

[1, 2, 3]

In [9]:
# python
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [10]:
# 多次元配列
arr = np.asarray([ [1,2,3], [4,5,6] ])
arr.shape

(2, 3)

In [11]:
# 要素が全部0の配列
np.zeros((2, 3))


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
# 要素がすべて1の配列
np.ones((2, 3))
       

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
# 要素を[0-1)の範囲でランダムに初期化する
np.random.rand(2, 3)


array([[ 0.206541  ,  0.49375447,  0.46993588],
       [ 0.88549407,  0.18344068,  0.33092919]])

In [14]:
# 要素を正規分布にのっとって生成する(2x3)
np.random.randn(2, 3)


array([[ 2.14474868, -0.0232562 , -0.71866837],
       [ 1.46372737, -0.15004684, -1.0564337 ]])

In [15]:
# 配列を３倍する
a = np.asarray([[1,2,3],[4,5,6]])
3 * a


array([[ 3,  6,  9],
       [12, 15, 18]])

In [16]:
# 配列同士の足し算
a = np.asarray([[1,2,3],[4,5,6]])
b = np.asarray([[2,3,4],[5,6,7]])
a + b


array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [17]:
# 配列同士の掛け算
a = np.asarray([[1,2,3],[4,5,6]])
b = np.asarray([[2,3,4],[5,6,7]])
a * b


array([[ 2,  6, 12],
       [20, 30, 42]])

In [18]:
# ２次元と１次元の掛け算
a = np.asarray([[1,2,3],[4,5,6]])
v = np.asarray([2,1,3])
a * v


array([[ 2,  2,  9],
       [ 8,  5, 18]])

In [19]:
# 二次元配列を一つの行列として演算を行うことも可能です。

M = np.asarray([[1,2,3], [2,3,4]])   # 2 x 3
N = np.asarray([[1,2],[3,4], [5,6]])  # 3 x 2

# この二つの配列の行列としての積を求めるには
M.dot(N)

# 2 x 2が返る

array([[22, 28],
       [31, 40]])

In [21]:
# numpyでは配列を様々な関数にいれることができます。この時、関数はそれぞれの要素に対して作用します。

a = np.asarray([[1,2], [3,1]])
np.log(a)


array([[ 0.        ,  0.69314718],
       [ 1.09861229,  0.        ]])

In [23]:
# numpyは配列の統計を取るのも得意です。まず100この乱数を生成します。

arr = np.random.rand(100)

# 配列の平均を取る
np.mean(arr)


0.5589438599926404

In [25]:
# 最大値、最小値

arr = np.random.rand(100)
np.max(arr) , np.min(arr)



(0.9960385688052944, 0.0035391742963464257)

In [26]:
# 標準偏差

arr = np.random.rand(100)
np.std(arr)


0.29663523881658149

In [27]:
# 和を得るには

arr = np.random.rand(100)
np.sum(arr)


51.453098760038905

In [29]:
# 二次元配列に関してはどの向きに統計を取るのかを指定することもできます。たとえば

arr = np.asarray([[1,2,3], [2,3,4]])
np.sum(arr, axis=0),np.sum(arr, axis=1)


(array([3, 5, 7]), array([6, 9]))

In [32]:
#ここまでを含めて、三次元空間内にある100個のベクトルの原点からのユークリッド距離の平均を求めるコードをnumpyを使って計算してみます。
#
#まずdata配列が、形が(100, 3)の配列で一列目がxx座標、二列目がyy座標、三列目がzz座標だとします。

data = np.random.randn(100, 3)
data[0:10]


array([[-0.01960147,  0.40465673,  0.19720983],
       [-1.9987349 , -0.20732259,  1.7200251 ],
       [ 0.68825603, -0.0515729 ,  1.67184912],
       [-0.07104807, -1.78522761,  0.64990881],
       [ 0.25719052,  0.61360626, -2.71415508],
       [-0.40354457,  1.02425604, -1.06193832],
       [ 1.2357994 , -0.24845209,  0.74214942],
       [ 0.91487894,  1.80467952,  1.35883392],
       [ 1.69943712,  0.34933497,  1.02912074],
       [ 0.30748971, -0.82743845,  0.14131404]])

In [33]:
# まずそれぞれの要素を自乗します。

squared = data**2
squared[0:10]

array([[  3.84217489e-04,   1.63747069e-01,   3.88917158e-02],
       [  3.99494120e+00,   4.29826550e-02,   2.95848635e+00],
       [  4.73696367e-01,   2.65976355e-03,   2.79507946e+00],
       [  5.04782855e-03,   3.18703762e+00,   4.22381462e-01],
       [  6.61469633e-02,   3.76512646e-01,   7.36663779e+00],
       [  1.62848223e-01,   1.04910044e+00,   1.12771300e+00],
       [  1.52720015e+00,   6.17284414e-02,   5.50785768e-01],
       [  8.37003466e-01,   3.25686815e+00,   1.84642963e+00],
       [  2.88808652e+00,   1.22034922e-01,   1.05908949e+00],
       [  9.45499220e-02,   6.84654392e-01,   1.99696567e-02]])

In [36]:
# 次にそれぞれの行に対して和を取ります。
squared_sum = np.sum(squared, axis=1)
# このときsquared_sumは一次元配列になります。
squared_sum[0:10]

array([ 0.203023  ,  6.9964102 ,  3.27143559,  3.61446691,  7.8092974 ,
        2.33966167,  2.13971436,  5.94030125,  4.06921094,  0.79917397])

In [37]:
# これに対して平方根を取ればそれぞれの点のユークリッド距離がわかります。

dist = np.sqrt(squared_sum)

dist[0:10]

array([ 0.45058074,  2.64507282,  1.80871103,  1.90117514,  2.79451201,
        1.52959526,  1.46277625,  2.43727332,  2.01722853,  0.89396531])

In [38]:
# この距離の平均を取れば

np.mean(dist)


1.6662361071010177