In [8]:
# https://keras.io/ja/layers/embeddings/
# 正の整数（インデックス）を固定次元の密ベクトルに変換します． 例）[[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]
# http://kento1109.hatenablog.com/entry/2017/12/02/114515

import numpy as np
from keras.models import Sequential
from keras.layers import Embedding
import datetime

print("%s start" % datetime.datetime.today())

# 20までの数字で10x5の行列生成
input_array = np.random.randint(20, size=(10, 5))

model = Sequential()
# input_dim:入力データの最大インデックス + 1
# output_dim: 密なembeddingsの次元数．, 
# input_length: 入力の系列長（定数）． この引数はこのレイヤーの後にFlattenからDenseレイヤーへ接続する際に必要です (これがないと，denseの出力のshapeを計算できません)．
# 入力データの種類が２０までなので、input_dimは20
# 1つの入力データを１０次元の蜜ベクトルに変換するのでoutput_dimは10 この数字は多分あまり意味はない?
# input_arrayの列数が５なのでinput_lengthは5 多分
model.add(Embedding(20, 10, input_length=5))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)

print("%s end" % datetime.datetime.today())


2018-03-07 17:13:29.720925 start
2018-03-07 17:13:29.771688 end


In [13]:
input_array[0:2]




array([[ 9,  6,  5,  2, 16],
       [11,  2,  2,  6,  9]])

In [12]:
# input_arrayの一つ一つのデータを１０次元の蜜ベクトルにしたということであろう
output_array[0:2]

array([[[ 0.0184721 , -0.01267653,  0.00904752, -0.03401458, -0.00626581,
          0.04169608, -0.03171185, -0.04509391,  0.00818732,  0.03686586],
        [-0.02961229, -0.01609151,  0.00980437, -0.01241324, -0.01736271,
          0.02143287,  0.01997726,  0.03955896,  0.04194834, -0.03870683],
        [-0.03149613,  0.01783235, -0.02435502, -0.01431438,  0.03774481,
         -0.04091991,  0.03230638,  0.01057551,  0.04519438, -0.01842938],
        [ 0.02854549,  0.01776375, -0.02642847,  0.00162339,  0.03910719,
          0.02169157, -0.03408506, -0.04658179,  0.01898718,  0.04598005],
        [ 0.04584498,  0.0240326 ,  0.00872178, -0.0119509 , -0.042976  ,
         -0.01834314,  0.00218909, -0.04601455, -0.04123963, -0.04438149]],

       [[ 0.02111248,  0.03295754, -0.00725074, -0.03979387,  0.00387195,
         -0.00638995,  0.02286189,  0.01282528,  0.02937026,  0.04338975],
        [ 0.02854549,  0.01776375, -0.02642847,  0.00162339,  0.03910719,
          0.02169157, -0.03408

In [4]:
# 乱数生成の動作確認
import numpy as np

# np.random.randint(20)
# 20までの数字で10x5の行列生成
np.random.randint(20, size=(10, 5))


array([[17,  9,  1, 11,  5],
       [17, 12,  6,  4, 15],
       [12, 13, 14, 10,  3],
       [19, 19, 16, 16, 17],
       [ 7,  9,  3, 13,  2],
       [12,  4, 12, 18,  2],
       [18, 15,  1,  5, 15],
       [ 0,  1, 18,  8,  3],
       [11, 18,  8, 10,  6],
       [ 6,  5,  3,  4, 17]])

In [28]:
# 実験
import numpy as np
from keras.models import Sequential
from keras.layers import Embedding
import datetime

print("%s start" % datetime.datetime.today())

# 1-9までの数字で3x2の行列生成
input_array = np.asarray([
                         [1,2,3],
                         [4,5,6]
])

model = Sequential()
# input_dim:入力データの最大インデックス + 1
# output_dim: 密なembeddingsの次元数．, 
# input_length: 入力の系列長（定数）． この引数はこのレイヤーの後にFlattenからDenseレイヤーへ接続する際に必要です (これがないと，denseの出力のshapeを計算できません)．
# 入力データの種類が1-6なので、input_dimは7
# 1つの入力データを8次元の蜜ベクトルに変換するのでoutput_dimは8 この数字は出力したい次元数
# input_arrayの列数が3なのでinput_lengthは3 多分
model.add(Embedding(7, 8, input_length=3))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)

print("%s end" % datetime.datetime.today())


2018-03-07 17:30:10.349089 start
2018-03-07 17:30:10.413181 end


In [29]:
input_array

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# 実行のたびに値が変わるようだ
output_array

array([[[-0.00321952, -0.0412927 ,  0.03926912, -0.0098901 ,  0.00121695,
         -0.01619692, -0.01308559,  0.01850671],
        [-0.03996754, -0.00904243,  0.02582434, -0.00305085,  0.02158827,
          0.02144363, -0.00673435,  0.00144339],
        [-0.04451327, -0.0247128 , -0.0494037 ,  0.0410302 , -0.00802755,
         -0.00798134, -0.00898333,  0.03766738]],

       [[-0.00930623, -0.00784091,  0.02067738, -0.04148411,  0.02703779,
          0.03211698,  0.01019262, -0.03806993],
        [-0.02774885, -0.04228967,  0.04954437, -0.04024577,  0.0248764 ,
         -0.012818  , -0.02574583, -0.00921291],
        [ 0.01641442, -0.04396258, -0.02723491, -0.02202097,  0.04178537,
         -0.04113647, -0.04022508,  0.04269603]]], dtype=float32)