In [44]:
import numpy as np
import keras

s = list('あいうえお')
x = []
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))

X = np.array(x)
X.resize(30,refcheck=False)
X = X.astype('float32')

y=1
Y = keras.utils.np_utils.to_categorical(y, 2)


In [ ]:
x

In [46]:
X

array([ 14909826.,  14909828.,  14909830.,  14909832.,  14909834.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.], dtype=float32)

In [ ]:
s

In [45]:
Y

array([[ 0.,  1.]])

In [2]:
import numpy as np
X=np.empty((0,30),float)

s = list('あいうえお')
x=[]
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))
xx = np.array(x)
xx.resize(30,refcheck=False)
xx = xx.astype('float32')
X=np.append(X,[xx],axis=0)

s = list('かきくけこ')
x=[]
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))
xx = np.array(x)
xx.resize(30,refcheck=False)
xx = xx.astype('float32')
X=np.append(X,[xx],axis=0)
X


array([[ 14909826.,  14909828.,  14909830.,  14909832.,  14909834.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.],
       [ 14909835.,  14909837.,  14909839.,  14909841.,  14909843.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.]])

In [3]:
X.shape

(2, 30)