In [44]:
import numpy as np
import keras

s = list('あいうえお')
x = []
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))

X = np.array(x)
X.resize(30,refcheck=False)
X = X.astype('float32')

y=1
Y = keras.utils.np_utils.to_categorical(y, 2)


In [ ]:
x

In [46]:
X

array([ 14909826.,  14909828.,  14909830.,  14909832.,  14909834.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.,
               0.,         0.,         0.,         0.,         0.], dtype=float32)

In [ ]:
s

In [45]:
Y

array([[ 0.,  1.]])

In [2]:
import numpy as np
X=np.empty((0,30),float)

s = list('あいうえお')
x=[]
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))
xx = np.array(x)
xx.resize(30,refcheck=False)
xx = xx.astype('float32')
X=np.append(X,[xx],axis=0)

s = list('かきくけこ')
x=[]
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))
xx = np.array(x)
xx.resize(30,refcheck=False)
xx = xx.astype('float32')
X=np.append(X,[xx],axis=0)
X


array([[ 14909826.,  14909828.,  14909830.,  14909832.,  14909834.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.],
       [ 14909835.,  14909837.,  14909839.,  14909841.,  14909843.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.,
                0.,         0.,         0.,         0.,         0.]])

In [3]:
X.shape

(2, 30)

In [45]:
import numpy as np

s = list('あいうえお')
x = []
for c in s:
  x.append(np.int.from_bytes(c.encode('utf-8'),'big'))


ss = str()
for xx in x:
    ss += bytearray(xx.to_bytes((xx.bit_length() + 7) // 8,'big')).decode(encoding='utf-8')

print(ss)
    
    

あいうえお


In [7]:
x.decode(encoding='utf-8')

AttributeError: 'list' object has no attribute 'decode'

In [8]:
print(str(x))

[14909826, 14909828, 14909830, 14909832, 14909834]


In [17]:
u'あいうえお'.encode('utf-8')

b'\xe3\x81\x82\xe3\x81\x84\xe3\x81\x86\xe3\x81\x88\xe3\x81\x8a'

In [14]:
type(x)

list

In [28]:
x[0].to_bytes((x[0].bit_length() + 7) // 8,'big').hex()

'e38182'

In [38]:
tmp = bytearray(x[0].to_bytes((x[0].bit_length() + 7) // 8,'big'))
tmp.append(128)

In [39]:
tmp

bytearray(b'\xe3\x81\x82\x80')

In [40]:
ba = bytearray()

In [41]:
ba

bytearray(b'')

In [43]:
bytearray(x[0].to_bytes((x[0].bit_length() + 7) // 8,'big')).decode(encoding='utf-8')

'あ'

In [60]:
np.array(x[0]).astype(bytes)

array(b'14909826', 
      dtype='|S21')